name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [21-ubuntu]
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/openjdk/jdk:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v2
      - run: ./gradlew check build publishToMavenLocal --stacktrace
      - uses: Juuxel/publish-checkstyle-report@v1
        if: ${{ failure() }}
        with:
          reports: |
            **/build/reports/checkstyle/*.xml
      - run: mkdir run && echo "eula=true" >> run/eula.txt
      - run: ./gradlew runAutoTestServer --stacktrace --warning-mode=fail
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts ${{ matrix.java }}
          path: |
            build/libs/
            ./*/build/libs/
