name: Build
on:
  push:
    branches:
      - "1.16"
  pull_request:
    branches:
      - "1.16"

concurrency:
  cancel-in-progress: true
  group: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  build:
    strategy:
      matrix:
        java: [21-ubuntu]
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/openjdk/jdk:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gradle/actions/wrapper-validation@v3
      - run: ./gradlew check build publishToMavenLocal --stacktrace
      - uses: Juuxel/publish-checkstyle-report@v1
        if: ${{ failure() }}
        with:
          reports: |
            **/build/reports/checkstyle/*.xml
      - run: mkdir run && echo "eula=true" >> run/eula.txt
      - run: ./gradlew runAutoTestServer --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts ${{ matrix.java }}
          path: |
            build/libs/
            ./*/build/libs/
